services:
  kejarbill-api:
    # build: .
    image: kejarbahasa/kejar-bill-api:dev
    container_name: kejarbill-api
    restart: always
    env_file:
      - .env
    networks:
      - postgre_default
      - redis_default

networks:
  postgre_default:
    external: true
  redis_default:
    external: true
